=== sjbarlas/Enterprise-Systems/SOLUTIONS/Lab4/invoice.xsd
<?xml version="1.0"?>
<xs:schema	xmlns:xs="http://www.w3.org/2001/XMLSchema" 
			targetNamespace="http://www.dit.ie"
			xmlns="http://www.dit.ie"
			elementFormDefault="qualified">
	<xs:element name="invoice">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="invoice_number" type="xs:positiveInteger"/>
				<xs:element name="invoice_date" type="xs:date"/>
				<xs:element name="invoice_total" type="xs:decimal"/>
				<xs:element name="issued_by" type="xs:string"/>
				<xs:element name="bill_to">
					<xs:complexType>
						<xs:sequence>
							<xs:element name="name" type="xs:string"/>
							<xs:element name="address">
								<xs:complexType>
									<xs:sequence>
										<xs:element name="number" type="xs:positiveInteger"/>
										<xs:element name="street" type="xs:string"/>
										<xs:element name="city" type="xs:string"/>
									</xs:sequence>
								</xs:complexType>
							</xs:element>
						</xs:sequence>
					</xs:complexType>
				</xs:element>
				<xs:element name="item" maxOccurs="unbounded" minOccurs="1">
					<xs:complexType>
						<xs:sequence>
							<xs:element name="item_name" type="xs:string"/>
							<xs:element name="price" type="xs:decimal"/>
							<xs:element name="quantity" type="xs:positiveInteger"/>
						</xs:sequence>
					</xs:complexType>
				</xs:element>
				<xs:element name="payment_information" type="xs:string"/>
			</xs:sequence>
		</xs:complexType>			
	</xs:element>
</xs:schema>

=== sjbarlas/Enterprise-Systems/SOLUTIONS/Lab4/invoice(4).xml
<?xml version="1.0"?>
<invoice	xmlns="http://www.dit.ie"
			xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" 
			xsi:schemaLocation="http://www.dit.ie invoice.xsd">
			
	<invoice_number>1</invoice_number>
	<invoice_date>2011-02-17</invoice_date>
	<invoice_total>15.00</invoice_total>
	<issued_by>Mark</issued_by>
	<bill_to>
		<name>John</name>
		<address>
			<number>1</number>
			<street>Main St</street>
			<city>Dundalk</city>
		</address>
	</bill_to>
	<item>
		<item_name>Jacket</item_name>
		<price>10.00</price>
		<quantity>3</quantity>
	</item>
	<payment_information>No additional info</payment_information>			
</invoice>
